# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9141c1517fe74d2e7011aa55fcdbfe1203d39ec0654dced45186b725fa66906710d18b9f4592e05ff046ce465eff59e1e2180cc4c11c46ba1e7b860a76c88d79

test:
  secret_key_base: fde38e28d57270383ea55680de5b6c42b9e9a5658a4b743f655c20cc7def2fda36a008e08512ae9f883a661038d973e273d079bfd73d99034afb1d5fa02b39cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
